// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoolBooks.Models
{
    public partial class Authors
    {
        [Key]
        public int AuthorID { get; set; }

        [StringLength(20, MinimumLength = 3)]
        [Required]
        public string FirstName { get; set; }

        [StringLength(30, MinimumLength = 3)]
        [Required]
        public string LastName { get; set; }
        public DateTime? Created { get; set; }
       


        public ICollection<BooksAuthors> BooksFromAutors { get; set; }
        public ICollection<Quotes> Quotes { get; set; }
    

    [NotMapped]
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

    }
}