// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CoolBooks.Models
{
    public partial class Books
    {
        //public Books()
        //{
        //    BooksAuthors = new HashSet<BooksAuthors>();
        //    BooksGenres = new HashSet<BooksGenres>();
        //    BooksUsers = new HashSet<BooksUsers>();
        //    Reviews = new HashSet<Reviews>();
        //}

        public int BooksID { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Title { get; set; }

        [StringLength(1000, MinimumLength = 3)]
        [Required]
        public string Description { get; set; }

        [StringLength(100, MinimumLength = 3)]
        [Required]
        public string ISBN { get; set; }

        [StringLength(100, MinimumLength = 3)]
        [Required]
        public string ImagePath { get; set; }


        public bool IsDeleted { get; set; }

        public DateTime? Created { get; set; }

        public bool IsBookOfTheWeek { get; set; }
        public bool? NewestBook { get; set; } 
        public bool MostLikedBook { get; set; } 
        public bool MostCommetedBook { get; set; } 
        public bool MostDislikedBook { get; set; } 

        public ICollection<BooksAuthors> AuthorsFromBooks { get; set; }
        public ICollection<BooksGenres> GenresFromBooks { get; set; }
        public ICollection<BooksUsers> BooksUsers { get; set; }
        public ICollection<Reviews> Reviews { get; set; }
        public ICollection<Quotes> Quotes{ get; set; }
    }
}