// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoolBooks.Models
{
    public partial class BooksAuthors
    {

      
        public int AuthorID { get; set; }
        public int BooksID { get; set; }

        public Authors Author { get; set; }
        public Books Books { get; set; }
    }
}