// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoolBooks.Models
{
    public partial class BooksUsers
    {
        [Key]
        public int UserID { get; set; }

        public int BooksID { get; set; }

        [ForeignKey(nameof(BooksID))]
        [InverseProperty("BooksUsers")]
        public virtual Books Books { get; set; }
        [ForeignKey(nameof(UserID))]
        [InverseProperty(nameof(UserInfo.BooksUsers))]
        public virtual UserInfo User { get; set; }
    }
}