// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CoolBooks.Areas.Identity;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace CoolBooks.Models
{
    public partial class BooksUsers
    {

        public int BooksID { get; set; }
        public Books Books { get; set; }


        public string ClientId { get; set; }

        public ApplicationUser Client { get; set; }

        //public int UserID { get; set; }
        //public UserInfo User { get; set; }
    }
}