// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CoolBooks.Models
{
    public partial class Books
    {
        //public Books()
        //{
        //    BooksAuthors = new HashSet<BooksAuthors>();
        //    BooksGenres = new HashSet<BooksGenres>();
        //    BooksUsers = new HashSet<BooksUsers>();
        //    Reviews = new HashSet<Reviews>();
        //}

        public int BooksID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ISBN { get; set; }
        public string ImagePath { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? Created { get; set; }
        //public int GenerID { get; set; }

        public ICollection<BooksAuthors> BooksAuthors { get; set; }
        public ICollection<BooksGenres> BooksGenres { get; set; }
        public ICollection<BooksUsers> BooksUsers { get; set; }
        public ICollection<Reviews> Reviews { get; set; }
    }
}