// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CoolBooks.Models
{
    public partial class Genres
    {
       
        public int GenreID { get; set; }

        [StringLength(100, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }

        [StringLength(1000, MinimumLength = 3)]
        [Required]
        public string Description { get; set; }
        public DateTime? Created { get; set; }

        public ICollection<BooksGenres> BooksFromGenres { get; set; }
    }
}