// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoolBooks.Models
{
    public partial class UserInfo
    {
        public UserInfo()
        {
            BooksUsers = new HashSet<BooksUsers>();
            Reviews = new HashSet<Reviews>();
        }

        [Key]
        public int UserInfoID { get; set; }
        public int? UserID { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        public string Adress { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        public string Created { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<BooksUsers> BooksUsers { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Reviews> Reviews { get; set; }

    }
}