// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace CoolBooks.Models
{
    public partial class UserInfo
    {
 
        public int UserInfoID { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public string Created { get; set; }

        public string UserID { get; set; }

        public IdentityUser Client { get; set; }
        //public ICollection<BooksUsers> BooksUsers { get; set; }
        //public ICollection<Reviews> Reviews { get; set; }
    }
}